### ISSUE TITLE
Update Scenarios for DVC 2.0

### ISSUE THREAD

**Issue by iesahin** [iterative/katacoda-scenarios#20]
Currently there are a few issues in documentation repo for katacoda scenarios. Basically these are not running because of a required system upgrade to Python 3.8. 

- [x] Update issue on docs: https://github.com/iterative/dvc.org/issues/1400
- [ ] GS docs need to be more actionable:  https://github.com/iterative/dvc.org/issues/1943
- [x] A mismatch for commands: https://github.com/iterative/dvc.org/issues/1586
- [x] A subtask in DVC 2.0 doc update: https://github.com/iterative/dvc.org/issues/2026
- [x] Adding tutorial to appropriate pages: https://github.com/iterative/dvc.org/issues/670

### Update 2021-03-08 

- Changed the title to DVC 2.0. This issue was originally for 2.0 anyway. Most of the work done up until now is for 2.0

**Comment by iesahin** [comment]
Could you arrange the permissions/membership so that I can take over updating katacoda? @shcheklein 

Thank you.

**Comment by shcheklein** [comment]
@iesahin I've added you to the repo. You can now do PRs and they are merged it will deployed I think. Feel free to merge them as you go, unless it's some substantial change to the content and you feel that review is needed

**Comment by iesahin** [comment]
Thank you.

**Comment by iesahin** [comment]
I have updated the [versioning](https://katacoda.com/dvc/courses/get-started/versioning) part.

**Comment by iesahin** [comment]
Changed the name because most of the parts require an update for 1.0 as well. After the release we can update the commands and breaking changes for 2.0

**Comment by jorgeorpinel** [comment]
Hi @iesahin 👋. I noticed you started committing directly to `master` recently (80 or so commits: https://github.com/iterative/katacoda-scenarios/compare/0f302dd...2993d87 up til now). It would be a better practice (and more readable repo history) to use PRs (from branches directly on this repo, no fork needed) even if you have `master` write access. Thanks!

![image](https://user-images.githubusercontent.com/1477535/110253289-208a2380-7f4f-11eb-9386-cf5c5c17ce66.png)
> See https://github.com/iterative/katacoda-scenarios/network

**Comment by jorgeorpinel** [comment]
> A subtask in DVC 2.0 doc update: iterative/dvc.org#2026

Seems like that should be a separate issue in this repo? I'd also add checkboxes to the description above for each Get Started chapter:

- [x] Initialize (done in https://github.com/iterative/katacoda-scenarios/compare/0f302dd...2993d87#diff-02011e81bf7e79c858402ec12982ff09a9158044b69e615f011daa672a8758fb) + #26
- [x] Versioning (in https://github.com/iterative/katacoda-scenarios/compare/0f302dd...2993d87#diff-7edffbe9d1139e787e8afb2b109d1f937aed0e9a807adc468832f75062eca29b) + #27
- [ ] [Accessing](https://katacoda.com/dvc/courses/get-started/accessing) #28
- [x] [Stages](https://katacoda.com/dvc/courses/get-started/stages) (in https://github.com/iterative/katacoda-scenarios/compare/0f302dd...2993d87#diff-be2db7b7a2d7f131d6139b0d003bea46ca0a44abf0ae9cf99f518bd5b25ffe9b) + #29

**Comment by jorgeorpinel** [comment]
Question: what's the purpose of updating scenarios but keep using 1.0? Should we focus on updating them with 2.0 along the way? Per https://github.com/iterative/dvc.org/issues/2026

**Comment by iesahin** [comment]
> Hi @iesahin 👋. I noticed you started committing directly to `master` recently (80 or so commits: [0f302dd...2993d87](https://github.com/iterative/katacoda-scenarios/compare/0f302dd...2993d87) up til now). It would be a better practice (and more readable repo history) to use PRs (from branches directly on this repo, no fork needed) even if you have `master` write access. Thanks!

@jorgeorpinel Hi. 👋🏼 I began writing with PRs but the iteration takes 2x time that way. You need to merge to `master` before seeing the effects in katacoda. There are no prior tests or whatnot. 80 commits mean ~80 PRs. I agree that it would be better documentation-wise but the workflow needs updates to the master for each commit, either merging from PR or by direct commits. 

I thought establishing a basic structure first and iterating with PRs is more reasonable. 

> Question: what's the purpose of updating scenarios but keep using 1.0? Should we focus on updating them with 2.0 along the way? Per iterative/dvc.org#2026

The initial title for this issue had _DVC 2.0_. Then, as a stable release was needed to install with `snap` or`apt`, I decided to stick to 1.x and changed the title. Then we talked with @shcheklein and he said it's better to just move ahead to 2.0. I updated the installation scripts to use `pip --pre` instead of `snap` and wrote _stages_, _pipelines_, _params_ etc. for 2.0 but forgot to update this issue's title. Currently, the scenarios don't (or shouldn't) contain any reference to `dvc run` and we'll have an _Experiments_ scenario this week. I will go back to earlier scenarios and change the commands to 2.0 versions. 

Almost all the content and scripts in scenarios required update. I didn't stick to the issues. (e.g. the scenarios weren't able to run because the containers were not able to install DVC in the first place.) I'll just review and check if the issues are done, move them here and see whether we have some missing items.

Thank you for reviewing all. 🙏🏼 Muchas gracias. I'll update the scenarios in PRs.

**Comment by jorgeorpinel** [comment]
> I began writing with PRs but the iteration takes 2x time that way.

Shouldn't take that much longer, maybe 10-20% extra time? But it's worth it. Without branching or PRs it's pretty hard to go back and find where/why things were updated. For example your recent PRs are very clear e.g. #31 fixes up the language in the GS/Init scenario. We can go there and comment on any further/pending issues related to that, etc. (divide and conquer). BTW we can make reviews before you merge PRs if you want, you just need to request a review before merging.

Look how much better organized the Git history is now, with branches (you can tell where they start from) that have all the commits, while `master` only has merges:

![image](https://user-images.githubusercontent.com/1477535/110403533-dda97800-8042-11eb-9d61-57945eb06935.png)

Finally, this kind of an industry standard for collaborative/public repos. Further reading if you're interested: https://www.gitkraken.com/learn/git/best-practices/git-branch-strategy.

**Comment by jorgeorpinel** [comment]
> we talked with @shcheklein and he said it's better to just move ahead to 2.0... I will go back to earlier scenarios and change the commands to 2.0 versions.

Sounds good!

> Almost all the content and scripts in scenarios required update.

Yes they were probably made for dvc 0.x still! At least now they run and have decent, updated explanations, which is the most important step 👍 

Looking forward to the 2.0 updates (again, feel free to request in-PR reviews before merging) @iesahin. Thanks

**Comment by jorgeorpinel** [comment]
See also https://github.com/iterative/dvc.org/issues?q=is%3Aissue+is%3Aopen+katacoda

**Comment by iesahin** [comment]
I think the portions related to katacoda in iterative/dvc.org#1943 are resolved. We can close this.
